# Generated by Django 3.1.5 on 2021-01-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='author',
            new_name='user',
        ),
    ]
