# Generated by Django 3.1.5 on 2021-01-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20210120_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.IntegerField(choices=[(1, 'Take Away'), (2, 'Fast Food'), (3, 'Casual Dining'), (4, 'Fine Dining'), (5, 'Bistro'), (6, 'Caffe'), (7, 'Buffet'), (8, 'Pub')], default=1),
        ),
    ]
