# Generated by Django 3.1.5 on 2021-01-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20210120_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.IntegerField(choices=[(1, 'Select category'), (2, 'Take Away'), (3, 'Fast Food'), (4, 'Casual Dining'), (5, 'Fine Dining'), (6, 'Bistro'), (7, 'Caffe'), (8, 'Buffet'), (9, 'Pub')], default=1),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='country',
            field=models.IntegerField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_level',
            field=models.IntegerField(choices=[(1, 'to 10$'), (2, 'from 10$ to 50$'), (3, 'more than 50$')], default=1),
        ),
    ]
