# Generated by Django 3.1.5 on 2021-01-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20210120_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='country',
            field=models.IntegerField(choices=[(1, 'Select country'), (2, 'Switzerland'), (3, 'Germany'), (4, 'Austria'), (5, 'Italy'), (6, 'Poland'), (7, 'Slovakia'), (8, 'Buffet')], default=1),
        ),
    ]
