# Generated by Django 3.1.5 on 2021-01-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210120_1011 2'),
        ('restaurant', '0005_auto_20210120_1026 2'),
        ('restaurant', '0006_auto_20210120_1028 2'),
        ('restaurant', '0007_auto_20210120_1029'),
    ]

    operations = [
    ]
