# Generated by Django 3.1.5 on 2021-01-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_merge_20210121_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.IntegerField(choices=[(1, 'Select category'), (2, 'Take Away'), (3, 'Fast Food'), (4, 'Casual Dining'), (5, 'Fine Dining'), (6, 'Bistro'), (7, 'Caffe'), (8, 'Buffet'), (9, 'Pub')], default=1),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='country',
            field=models.IntegerField(choices=[(1, 'Select country'), (2, 'Switzerland'), (3, 'Germany'), (4, 'Austria'), (5, 'Italy'), (6, 'Poland'), (7, 'Slovakia'), (8, 'Buffet')], default=1),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_level',
            field=models.IntegerField(choices=[(1, 'to 10$'), (2, 'from 10$ to 50$'), (3, 'more than 50$')], default=1),
        ),
    ]
