# Generated by Django 3.1.5 on 2021-01-19 09:11

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.user.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='user',
            name='things_user_love',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
